language: go
services:
- docker


go:
  - '1.12'

go_import_path: github.com/IBM/multicloud-operators-subscription-release

git:
  depth: false
  
branches:
  only:
    - master
    # release tags
    - /^v\d+\.\d+\.\d+.*/

stages:
  - lint
  - test
  - build
  - multiarch

install:
  # - git clone https://github.com/IBM/multicloud-operators-subscription-release.git multicloud-operators-subscription-release
  - git clone https://github.com/itdove/multicloud-operators-subscription-release.git multicloud-operators-subscription-release
  - cd multicloud-operators-subscription-release
  # - git checkout -qf $BUILD_COMMIT

before_script:
  - source travis-env.sh
  - make init
  - make docker:login

jobs:
  include:
    - stage: lint
      name: Perform linting before any jobs trigger
      script:
        - make lint fmt
  
    - stage: test
      name: Test x86 image
      os: linux
      script:
      - make test

cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin

    
notifications:
  email:
    on_success: never
