---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicloud-operators-subscription-release
rules:
- apiGroups:
  - multicloud-apps.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicloud-operators-subscription-release-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: multicloud-operators-subscription-release
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multicloud-operators-subscription-release-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicloud-operators-subscription-release
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-operators-subscription-release
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicloud-operators-subscription-release
  template:
    metadata:
      labels:
        name: multicloud-operators-subscription-release
    spec:
      serviceAccountName: multicloud-operators-subscription-release
      volumes:
      - name: charts
        emptyDir: {}
      containers:
      - name: multicloud-operators-subscription-release
        # Replace this with the built image name
        image: quay.io/open-cluster-management/multicloud-operators-subscription-release
        command:
        - multicloud-operators-subscription-release
        imagePullPolicy: Always
        env:
        - name: CHARTS_DIR
          value: "/charts"
        - name: WATCH_NAMESPACE
          # valueFrom:
          #   fieldRef:
          #     fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "multicloud-operators-subscription-release"
        volumeMounts:
        - name: charts
          mountPath: "/charts"
        securityContext:
          # procMount: Default
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
